# Generated by Django 2.2.13 on 2020-11-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_list',
            name='price',
            field=models.FloatField(default=100.0),
        ),
    ]
